apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: abc
type: Opaque
data:
  mongo-root-username: dXNlcmh3aDM=     # base64 of "mongouser"
  mongo-root-password: dXNlcmh3aDQ0Mw==  # base64 of "password123"

