apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  namespace: abc
spec:
  selector:
    app: mun
  ports:
    - protocol: TCP
      port: 27017        # Service port
      targetPort: 27017  # Container port
  type: ClusterIP        # Internal access only. Use LoadBalancer for external
