apiVersion: v1
kind: Service
metadata:
  name: mongoexpress-service
  namespace: abc
spec:
  selector:
    app: mongoexpress
  ports:
    - protocol: TCP
      port: 8081      # Service port
      targetPort: 8081  # Container port
      nodePort: 30030
  type: NodePort      # e
